### ISSUE TITLE
Problems with public URL

### ISSUE THREAD

**Issue by fenderislife** [MrRonfo/openhab-smarther#4]
Hello MrRonfo, 
this follows our communication on 
https://community.openhab.org/t/bticino-smarther-thermostat/39621

I obtained new "Client ID" and "Client Secret" for a new application on Legrand website. I registered with a public URL I verified: it is my ddns (which I don't show here for security reasons), and I implemented it in both ``notify url`` and ``redirect uri`` 
``
redirect_uri="http://xxx.existingddns.com:12345/smarther/smarther-auth.php"
notify_url="http://xxx.existingddns.com:12345/smarther/smarther-c2c.php"
``
I tested the public URL with a "hello world" php script, which works.
"http://xxx.existingddns.com:12345/smarther/hello.php"

Owner of both files is ``www-data:adm``.

``smarther-api.sh`` is correctly compiled.

I get the long url when I execute ``./smarther-api.sh`` but only after typing ``exit``

Anyway I obtained ``authorization.json`` and moved it to the correct folder.

When I type ``smarther-api.sh get_status`` I get nothing. 
When I type ``exit`` I get:

``
./smarther-api.sh: riga 152: /etc/openhab2/scripts/smarther/data/refresh.json: Permesso negato
/etc/openhab2/scripts/smarther/data/refresh.json: File o directory non esistente
chown: impossibile accedere a '/etc/openhab2/scripts/smarther/data/refresh.json': File o directory non esistente
/etc/openhab2/scripts/smarther/data/refresh.json: File o directory non esistente
date: data "@" non valida
./smarther-api.sh: riga 93: /etc/openhab2/scripts/smarther/log/smarther.log: Permesso negato
./smarther-api.sh: riga 93: /etc/openhab2/scripts/smarther/log/smarther.log: Permesso negato
{"rsptype":"get_status","rspcode":401,"errormsg":"(get_status) Unauthorized. Supplied access token is invalid."}
``
Do you have any hints?
Thank you.

**Comment by MrRonfo** [comment]
Hi @fenderislife, it seems to me you're experiencing a write permission issue on `refresh.json` file when the script tries to persist the 1st received accessToken from the OAuth2 process.

Could you please dump here the content of both `/scripts/smarther` and `/scripts/smarther/data` directories ?
Using `ls -la` or similar, to have the info of user:group for each file as well.

Thanks!

**Comment by fenderislife** [comment]
Sure, here they are:
``
**pi@raspberrypi:/etc/openhab2/scripts/smarther $ ls -l**
totale 28
drwxr-xr-x 2 openhab openhab  4096 mag  5 07:58 data

drwxr-xr-x 2 openhab openhab  4096 mag  5 08:02 log

-rwxrwxr-x 1 openhab openhab 17515 mag  1 17:18 smarther-api.sh
``

``
**pi@raspberrypi:/etc/openhab2/scripts/smarther/data $ ls -l**

totale 4

-rwxrwxrwx 1 openhab openhab 1040 mag  4 13:57 authorization.json
``

Thank you

**Comment by MrRonfo** [comment]
Hmmm... you're launching `smarther-api.sh` with user `pi`.
Both `/data` and `/log` directory are owned by user `openhab`, with no write permission neither to members of `openhab` group nor to other users.

I think to make the things work in your case you should:
```
sudo chmod 775 /data
sudo chmod 775 /log
```
and add user `pi` as member of the `openhab` group, for example using:
```
usermod -a -G openhab pi
```

I've also updated the `smarther-api.sh` script, aiming to automatically create the `refresh.json` file with the right permissions and the same user:group of the script (no matter the user you run it with).

Let me know ;)
Cheers

**Comment by fenderislife** [comment]
Thank you.
I did what you suggested.
I succeeded with access to refresh.json but still had problems with smarther.log.
Then I changed owner rights to it and i succeeded to obtain the status of my Smarther.
````
pi@raspberrypi:/etc/openhab2/scripts/smarther $ ./smarther-api.sh get_status
{"rsptype":"get_status","rspcode":200,"function":"HEATING","mode":"AUTOMATIC","setpoint":16,"program":2,"time":"forever","tempformat":"C","status":"INACTIVE","temperature":20.2,"humidity":63.9}
````
**Problem 1**
Then I added bindings and transformations, configured the item, copied the files in the correct places and merged ````smarther.sitemap```` into ````default.sitemap````.
Unfortunately the results are not as expected. Please find attached in the .jpg file what I get in the Control tab of my Paper UI.

![log](https://user-images.githubusercontent.com/50184742/57200433-4a0d4900-6f8c-11e9-9970-52c119cda102.jpg)

I even changed ``user:group`` of each file to ``openhab:openhab`` and changed privileges to all of them, but it didn't do the job. 

**Problem 2**
Moreover, when I type
````
pi@raspberrypi:/etc/openhab2/scripts/smarther $ ./smarther-api.sh set_subscription
````
I get
````
{"rsptype":"set_subscription","rspcode":400,"errormsg":"(set_subscription) Bad Request"}
````
I even added writing rights to ````smarther-c2c.php````  and included ```` pi ```` in ````adm ```` group  
This is my directory:
````
pi@raspberrypi:/var/www/html/smarther $ ls -la
totale 28
drwxr-xr-x 2 www-data adm  4096 mag  5 23:17 .
drwxrwxr-x 3 root     root 4096 apr 25 00:40 ..
-rw-r--r-- 1 www-data adm  3665 apr 25 22:49 23.html
-rw-r--r-- 1 www-data adm   113 mag  1 20:47 hello.php
-rw-r--r-- 1 www-data adm   435 mag  1 23:11 smarther-auth.php
-rwxrwxrwx 1 www-data adm  6533 mag  5 22:53 smarther-c2c.php
````
"REST_API", is correctly configured in ``smarther-c2c.php`` as "http://192.168.x.xxx:8080/rest/").

Thank you again for your help.

**Comment by MrRonfo** [comment]
Glad that you now succeeded in properly running the script.
1st mission accomplished ;)

**Problem 1** - not a real problem: the one you named "Smarther Thermostat" is actually the Exec Binding needed to execute the script from inside OH2.
You can see its `output` channel correctly reported the result of last script execution (a `get_status` call, in that case), the same way and format as it echoes when run on command line.
The same binding is configured as `SMA_Thermo_Send` items in `smarther.items` file and used by the rules in `smarther.rules` file to correctly populate the other `SMA_Thermo_*` items (which represents your device).

**Problem 2** - error 400 could also be due to a misconfiguration of `notify_url` param inside `smarther-api.sh`; please check the public URL in there is well formed.
Otherwise, any useful log you can post here from `/var/log/php/` ?
Perhaps content of `smarther-c2c.log` file...

Cheers

**Comment by fenderislife** [comment]
**Problem 1** - I thought that the "Control" tab could have allowed me to control the parameters of my Smarther, but maybe I'm wrong. I have no experience with OpenHab and have still not configured my Home Bulider or HabPanel, I'm just adding my devices for now. 
I must however say that controlling my Smarther via OpenHab app for Android works like a charm! Even better than bticino app.

 **Problem 2** - unfortunately `notify_url` redirects to `smarther-c2c.php` in the correct way (it's the same path I used for `redirect_uri` - with the exception of the `.php` file, of course, since both `smarther-c2c.php` and `smarther-auth.php` belong to the same directory).
I can't even publish any log from `/var/log/php/` , not even `smarther-c2c.log` file, because it is an empty file (0 bytes).

One thought: maybe Azure needs a https:// address, nota a http:// like mine?

Thank you again

**Comment by MrRonfo** [comment]
Hi,

**Problem 1** - so you've successfully setup the Smarther items in BasicUI, haven't you?
Problem solved in that case ;)

**Problem 2** - I didn't notice it before but, indeed, yes you're right as it seems that only https endpoints are supported by Cloud2Cloud notification for Smarther (see "important" note [here](https://developer.legrand.com/tutorials/subscription-to-cloud-to-cloud-notifications-c2c-webhooks/)).
Is http your only option or can you setup some reverse proxy to use https (like Nginx) ?

Cheers

**Comment by fenderislife** [comment]
Thank you.
I'm trying to set up Nginx as a reverse proxy to use https, but I believe it is beyond my skills.
Anyway thank you again for your help. I believe the issue can be closed.
At least you had a beta tester for openhab-smarther!
