### ISSUE TITLE
No MS Azure Cloud2Cloud notifications

### ISSUE THREAD

**Issue by fenderislife** [MrRonfo/openhab-smarther#5]
Dear Mr_Ronfo,
I finally managed to configure my nginx to have a SSL connection.
I typed
``
./smarther-api.sh set_subscription
``
And I got the correct message
``
{"rsptype":"set_subscription","rspcode":201,"subscriptions":{"subscriptionId":"xxxxxx-yyyy-zzzz-aaaa-bbbbb"}}
``
Unfortunately, I still have no updates on my thermostat status both on temperature and humidity.
Is there a log I can post?
Thank you

**Comment by MrRonfo** [comment]
Hi @fenderislife , deeply sorry, I was away and received no notification of new open issue.
Have you already managed to solve the problem or still need support on it ?
Cheers

**Comment by fenderislife** [comment]
Hi MrRonfo,
I have not solved the problem. I believe It Is due to my nginx configuration. The issue can be closed then.
Thank you
